<h4>| Base sobre quest√µes que tratam de atividades que os estudantes realizam </h4>

In [1]:
from diskcache import Cache
from appdirs import user_cache_dir

cache = Cache(user_cache_dir("cache"))
GENERATED_DATASET_PATH = cache.get("GENERATED_DATASET_PATH")

In [2]:
import pandas as pd
from pycaret.classification import *

df_atv = pd.read_csv(f'{GENERATED_DATASET_PATH}/df_atv.csv')

In [7]:
s = setup(data=df_atv, target='curso', train_size=0.8, session_id=123)

In [5]:
best = compare_models()

#### üìä Tune_Model - Aplicando Hiperpar√¢metros

##### üíªÔ∏è Extra Trees Classifier

In [5]:
et = create_model('et')
tuned_et = tune_model(et, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Random Forest Classifier

In [6]:
rf = create_model('rf')
tuned_rf = tune_model(rf, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Dummy Classifier

In [7]:
dummy = create_model('dummy')
tuned_dummy = tune_model(dummy, n_iter=50, optimize='F1')

Fitting 10 folds for each of 4 candidates, totalling 40 fits

##### üíªÔ∏è Gradient Boosting Classifier

In [8]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Ada Boost Classifier

In [9]:
ada = create_model('ada')
tuned_ada = tune_model(ada, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

##### üíªÔ∏è Linear Discriminant Analysis

In [10]:
lda = create_model('lda')
tuned_lda = tune_model(lda, n_iter=50, optimize='F1')

Fitting 10 folds for each of 36 candidates, totalling 360 fits

##### üíªÔ∏è Logistic Regression

In [11]:
lr = create_model('lr')
tuned_lr = tune_model(lr, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Light Gradient Boosting Machine

In [12]:
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Ridge Classifier

In [13]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è SVM - Linear Kernel

In [14]:
svm = create_model('svm')
tuned_svm = tune_model(svm, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è K Neighbors Classifier

In [15]:
knn = create_model('knn')
tuned_knn = tune_model(knn, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Decision Tree Classifier

In [16]:
dt = create_model('dt')
tuned_dt = tune_model(dt, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Quadratic Discriminant Analysis

In [17]:
qda = create_model('qda')
tuned_qda = tune_model(qda, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### üíªÔ∏è Naive Bayes

In [18]:
nb = create_model('nb')
tuned_nb = tune_model(nb, n_iter=50, optimize='F1')

Fitting 10 folds for each of 28 candidates, totalling 280 fits