<h4>| Base contendo questões referentes à infraestrutura</h4>

In [3]:
from diskcache import Cache
from appdirs import user_cache_dir

cache = Cache(user_cache_dir("cache"))
GENERATED_DATASET_PATH = cache.get("GENERATED_DATASET_PATH")

In [4]:
import pandas as pd
from pycaret.classification import *

df_estrutura = pd.read_csv(f'{GENERATED_DATASET_PATH}/df_estrutura.csv')

In [5]:
s = setup(data=df_estrutura, target='curso', train_size=0.8, session_id=123)

In [6]:
best = compare_models()

#### 📊 Tune_Model - Aplicando Hiperparâmetros

##### 💻️ Logistic Regression

In [7]:
lr = create_model('lr')
tuned_lr = tune_model(lr, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Extra Trees Classifier

In [8]:
et = create_model('et')
tuned_et = tune_model(et, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

##### 💻️ Ridge Classifier

In [9]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Linear Discriminant Analysis

In [10]:
lda = create_model('lda')
tuned_lda = tune_model(lda, n_iter=50, optimize='F1')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting 10 folds for each of 36 candidates, totalling 360 fits

##### 💻️ K Neighbors Classifier

In [11]:
knn = create_model('knn')
tuned_knn = tune_model(knn, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Random Forest Classifier

In [12]:
rf = create_model('rf')

# Otimizando os hiperparâmetros;
tuned_rf = tune_model(rf, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ SVM - Linear Kernel

In [13]:
svm = create_model('svm')
tuned_svm = tune_model(svm, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Gradient Boosting Classifier

In [14]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Ada Boost Classifier

In [15]:
ada = create_model('ada')
tuned_ada = tune_model(ada, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

##### 💻️ Decision Tree Classifier

In [16]:
dt = create_model('dt')
tuned_dt = tune_model(dt, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Dummy Classifier

In [17]:
dummy = create_model('dummy')
tuned_dummy = tune_model(dummy, n_iter=50, optimize='F1')

Fitting 10 folds for each of 4 candidates, totalling 40 fits

##### 💻️ Naive Bayes

In [18]:
nb = create_model('nb')
tuned_nb = tune_model(nb, n_iter=50, optimize='F1')

Fitting 10 folds for each of 28 candidates, totalling 280 fits

##### 💻️ Quadratic Discriminant Analysis

In [19]:
qda = create_model('qda')
tuned_qda = tune_model(qda, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits