<h4>| Base contendo questões referentes à infraestrutura</h4>

In [ ]:
import os
import pandas as pd
from dotenv import load_dotenv
from pycaret.classification import *

load_dotenv()

PATH = os.getenv("GENERATED_DATASET_PATH")

df_estrutura = pd.read_csv(f'{PATH}/df_estrutura.csv')

In [9]:
s = setup(data=df_estrutura, target='curso', train_size=0.8, session_id=123)

In [10]:
best = compare_models()

#### 📊 Tune_Model - Aplicando Hiperparâmetros

##### 💻️ Logistic Regression

In [11]:
lr = create_model('lr')
tuned_lr = tune_model(lr, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Extra Trees Classifier

In [12]:
et = create_model('et')
tuned_et = tune_model(et, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

##### 💻️ Ridge Classifier

In [13]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Linear Discriminant Analysis

In [14]:
lda = create_model('lda')
tuned_lda = tune_model(lda, n_iter=50, optimize='F1')

Fitting 10 folds for each of 36 candidates, totalling 360 fits

##### 💻️ K Neighbors Classifier

In [15]:
knn = create_model('knn')
tuned_knn = tune_model(knn, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Random Forest Classifier

In [16]:
rf = create_model('rf')

# Otimizando os hiperparâmetros;
tuned_rf = tune_model(rf, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

##### 💻️ SVM - Linear Kernel

In [17]:
svm = create_model('svm')
tuned_svm = tune_model(svm, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Gradient Boosting Classifier

In [18]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Ada Boost Classifier

In [19]:
ada = create_model('ada')
tuned_ada = tune_model(ada, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Decision Tree Classifier

In [20]:
dt = create_model('dt')
tuned_dt = tune_model(dt, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits

##### 💻️ Dummy Classifier

In [21]:
dummy = create_model('dummy')
tuned_dummy = tune_model(dummy, n_iter=50, optimize='F1')

Fitting 10 folds for each of 4 candidates, totalling 40 fits

##### 💻️ Naive Bayes

In [22]:
nb = create_model('nb')
tuned_nb = tune_model(nb, n_iter=50, optimize='F1')

Fitting 10 folds for each of 28 candidates, totalling 280 fits

##### 💻️ Quadratic Discriminant Analysis

In [23]:
qda = create_model('qda')
tuned_qda = tune_model(qda, n_iter=50, optimize='F1')

Fitting 10 folds for each of 50 candidates, totalling 500 fits